### ISSUE TITLE
gmon_var folder is empty

### ISSUE THREAD

**Issue by xunzhang** [wenglingmei/vprofAE#1]
I set up the environment and follow the steps to profiling my simple example code. Following the intuition of the paper, vprof should output the funcion `run` as the root cause. But I got `gmon_var` folder empty while other files looks normal. Is that because the code is running too fast? How to correctly generate gmon_var. Thanks!
```
#include <unistd.h>
#include <cstdlib>

int global_var1 = 1;
int global_var2 = 2;


int testphi = 0;


int foo(int x){ 
    for (int i = 0; i < 40000; ++i) {
      x = i;
      usleep(1);
    }   
    return x;
}

int func(int x){ 
    int g = 0;
    for (int i = 0; i < 1000000; ++i) {
      g += i % 100000;
      usleep(1);
    }   
    return g % 5;
}


int run(int v) {
  int z = 0;
  if (v > 5) {
    z = func(global_var2); // bug run when given v is large
  } else {
    z = 2;
  }
  return z;
}

int main(int argc, char** argv){
    int t = atoi(argv[1]);
    int x = global_var1;
    int z = 0;
    int y = foo(x);
    int k = t;
    z = run(k);
    
    return 0;
}

```

**Comment by wenglingmei** [comment]
First of all, you need to make sure the variables are present in the schema file. Even if value samples are not captured due to running too fast, you should still get gmon_var files with meta data.  I would suggest trying the Redis case to make sure the setting is correct.

**Comment by xunzhang** [comment]
The Redis case running correctly. Will figure out why, thanks anyway!

**Comment by xunzhang** [comment]
Hi, can I have a follow-up question? For MySQL, if I only compile a component(e.g., innobase), when translating schema to get the offset and register, do I need to specify the big mysqld as the executable? Can I use object file instead? Thanks!
